theme: mimima
title: My Github Page
author: wordlesspureimagination
email: wordlesspureimagination@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  我的 GitHub Page 项目学习
# social links
github_username:  wordlesspureimagination # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
